### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by devincapriola** [YoungSeng/DiffuseStyleGesture#18]
in the training part 

(2) Process ZEGGS dataset
```
cd ./main/mydiffusion_zeggs/
python zeggs_data_to_lmdb.py
``` 

i am getting this error
```
001_Neutral_0_mirror_x_0_9
normalize audio: 001_Neutral_0_mirror_x_0_9.wav
Traceback (most recent call last):
  File "zeggs_data_to_lmdb.py", line 174, in <module>
    make_zeggs_dataset(source_path, target)
  File "zeggs_data_to_lmdb.py", line 156, in make_zeggs_dataset
    all_poses = make_zeggs_subdataset(source_path_train, target_train, all_poses)
  File "zeggs_data_to_lmdb.py", line 134, in make_zeggs_subdataset
    subprocess.call(cmd)
  File "C:\Users\PC\anaconda3\envs\DiffuseStyleGesture\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\PC\anaconda3\envs\DiffuseStyleGesture\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\PC\anaconda3\envs\DiffuseStyleGesture\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by YoungSeng** [comment]
The problem seems to be that 

https://github.com/YoungSeng/DiffuseStyleGesture/blob/fad55f6af2481f2ec6889156930d7ee9e472e1bf/main/mydiffusion_zeggs/zeggs_data_to_lmdb.py#L133

does not run correctly.

Have you installed `ffmpeg` correctly and is is running the code in a windows environment? I would recommend running the code in a Linux environment. Also suggest trying DiffuseStyleGesture+: 
https://github.com/YoungSeng/DiffuseStyleGesture/tree/master/BEAT-TWH-main
