### ISSUE TITLE
在终端运行指令报错      NameError: name 'inference' is not defined

### ISSUE THREAD

**Issue by sjysc** [YoungSeng/DiffuseStyleGesture#45]
Traceback (most recent call last):
  File "sample.py", line 140, in <module>
    main(config, save_dir, config.model_path, audio_path=None, mfcc_path=None, audiowavlm_path=config.audiowavlm_path, max_len=config.max_len)
  File "sample.py", line 98, in main
    inference(args, wavlm_model, mfcc, sample_fn, model, n_frames=max_len, smoothing=True, SG_filter=True, minibatch=True, skip_timesteps=0, style=style, seed=123456)      # style2onehot['Happy']
NameError: name 'inference' is not defined

**Comment by YoungSeng** [comment]
确保按照`readme`中的步骤，inference函数就在这里

https://github.com/YoungSeng/DiffuseStyleGesture/blob/f78242bbdeca945a3f15f44b1e0497a8b6bdbfea/main/mydiffusion_zeggs/sample.py#L210
