### ISSUE TITLE
python end2end.py --config=./configs/DiffuseStyleGesture .yml --no_cuda 0 --gpu 0

### ISSUE THREAD

**Issue by sjysc** [YoungSeng/DiffuseStyleGesture#46]
Traceback (most recent call last):
  File "end2end.py", line 70, in <module>
    main(config, mydevice)
  File "end2end.py", line 31, in main
    pose_resampling_fps=args.motion_resampling_framerate, model='WavLM', device=device)
  File "/home/ubuntu/DiffuseStyleGesture-master/main/mydiffusion_zeggs/data_loader/lmdb_data_loader.py", line 31, in __init__
    subdivision_stride, pose_resampling_fps, device=device)
  File "/home/ubuntu/DiffuseStyleGesture-master/main/mydiffusion_zeggs/data_loader/data_preprocessor.py", line 44, in __init__
    self.src_lmdb_env = lmdb.open(clip_lmdb_dir, readonly=True, lock=False)
lmdb.Error: ../../ubisoft-laforge-ZeroEGGS-main/data/processed_v1/processed/train/train_lmdb/train_lmdb/: No such file or directory

**Comment by YoungSeng** [comment]
见[这个](https://github.com/YoungSeng/DiffuseStyleGesture/issues/47 )；另外可以尝试一下DiffuseStyleGesture+，使用h5保存的，没有此类问题
